### ISSUE TITLE
Possibility to add classes to a fixture?

### ISSUE THREAD

**Issue by CptMeatball** [Samuell1/contenteditor-plugin#42]
Would it be possible to add classes to a fixture?

**Comment by jonathan-hc** [comment]
+1 

I used contenteditor "link" tool for some links that were styled as buttons using classes and as soon as I saved my edits, the classes were stripped off leaving the link a plain one.

**Comment by ghost** [comment]
+1000 here, I just wanted to post the same issue and discover yours. Why closed without answers ?

Personaly, I use fixture a lot because I want my clients to be able to edit texts on their sites, but not the design neither the semantic, so I don't want to let them to play with different tags.

But I still want to be able to easily apply styles to that elements, and using class would greatly help for that purpose.

I would wrap the fixture in another tag with the class I want, but, as most october CMS user. I always try to remove a wrapper when I can (to have lighter, more readable, elegant code).

For this reason, adding class directly to the fixture element would be the best option.

Best regards,

Alex

**Comment by CptMeatball** [comment]
Since opening this issues, we've tackled this problem by wrapping the element with a div. In CSS apply that styling to the html element. (like @Alex360hd already pointed out). It's the same principe, just a bit messier.

    .lead h1 {
        // styles here
    }

**Comment by ghost** [comment]
[PR added](https://github.com/Samuell1/contenteditor/pull/57), even if the wrapper solution works. I think it's nicer to have class support directly in content editor component (at lease for fixture, where it make sense).

**Comment by samuelpatro** [comment]
@Alex360hd Thanks for pr!

But I want to complete rework content editor when Content Tools will be ported to ES6. Then it should be easier to change, customize and many better features :)

**Comment by ghost** [comment]
Nice !

Do you think you can commit the PR by waiting the new version ? I'm actually building a website by using this method, would like to know if the PR will be commited before I finish it or if I have to go back to the old method by adding a wrapper with the class I need.
