### ISSUE TITLE
Fixtures not rendering when not logged in

### ISSUE THREAD

**Issue by mpetricek** [Samuell1/contenteditor-plugin#47]
Hi,

I don't know why but fixtures and tags are not rendered when I visit page as visitor not logged in. Do you have any idea?

Thank you

**Comment by samuelpatro** [comment]
Hey, what version do you using?

**Comment by mpetricek** [comment]
1.0.9

**Comment by mpetricek** [comment]
Now I was testing it and it doesn't save tags at all (Bold etc.)

**Comment by samuelpatro** [comment]
Do you get any errors in console?

**Comment by mpetricek** [comment]
Nope

**Comment by samuelpatro** [comment]
And without fixtures everything works fine?

**Comment by mpetricek** [comment]
Now  when I was testing it it wasn't working neither. Tags like `<p> </p>` are there but `<b>` `<i>` are rendered at first when I save it but on reload they are not there anymore no matter what.

**Comment by samuelpatro** [comment]
Do you using latest version of OctoberCMS?

I can look more on it tomorrow can you provide your code what you used?

**Comment by mpetricek** [comment]
Yes, build 431

**Comment by mpetricek** [comment]
I think that problem is on my side with jQuery. I'm very sorry and I'll report back

**Comment by mpetricek** [comment]
Ok I figured out why my jQuery was stripping "bold" tags and so on. 

Now the only problems are not working "fixtures". They work when I'm logged but when not the fixture tags (p, h2) are stripped.

**Comment by ghost** [comment]
Hi,

I just wanted to post the exact same issue and I discovered yours.

When you use fixture, for example that : 

    <div class="container">
        {% component 'editor' file="footer/footer-top" fixture="h2" %}
    </div>

When you are logged in as admin (and so you have access to content editor), the rendered HTML is like that : 

    <div class="container">
      <h2 data-fixture="" data-ce-tag="p" data-component="editor::onSave" data-file=".frfooter/footer-top" data-tools="paragraph,bold">Contact-us</h2>
    </div>

The same block when I'm logged out : 

    <div class="container">Contact-us</div>

As you can see, the whole h2 tag disappeared.

You can also notice that the rendered html have an empty data-fixture (that should probably be filled with "h2") and there is a data-tools attribute that should not be here.

It's probably  because I have others parts of the page that I edit with content tools too, and it seems to bring conflicts.

EDIT : I think I understand what happens. If I go to CMS > Content and I edit my ".frfooter/footer-top" file, I see only "Contact-us" in it (without any tags).

Non admin users don't have any access to content editor (and it's great because I don't want everybody to be able to edit my website), but as a result, content editor can't be initialized and October CMS just load the content in my .frfooter/footer-top file (so "Contact-us" without any tags).

To patch this, I think that when you use the fixture property, you should save the fixture tag in the content file, so my .frfooter/footer-top file would contain 

    <h2>Contact-us</h2> 

instead of just "Contact-us"

**Comment by samuelpatro** [comment]
Fixed in new version 1.1.0!

**Comment by ghost** [comment]
Wow what a reactivity ! I just posted 👍
